"""Provides all activities"""
from activities import (
    admin_adjustment, approve_received_inventory, 
    complete_destruction, 
    complete_oil_extraction, 
    create_activity_log, 
    create_batch, 
    create_mother, 
    update_mother_status,
    create_mother_batch, 
    transfer_mother_plants_to_mother_batch,
    transfer_batch_plant_to_mother_batch,
    create_rule, destroy_material, germinate_seeds,
    org_update_theme, propagate_cuttings,
    queue_for_destruction, receive_inventory, transfer_inventory,
    update_room, update_rule, update_stage, update_inventory_name, unset_room,
    batch_record_harvest_weight, metrics_collect_branch_count, metrics_collect_bud_density,
    metrics_collect_bud_moisture, metrics_collect_bud_diameter, metrics_collect_height,
    metrics_collect_internodal_space, metrics_collect_trichome_color,
    metrics_record_deficiency, plants_add_pesticide, plants_add_fertilizer, plants_defoliate, plants_flush, plants_add_ipm,
    plants_prune, batch_record_final_yield, batch_record_dry_weight, split_batch, batch_visual_inspection,
    create_sample, sample_sent_to_lab,
    sample_lab_result_received, create_lot, create_sku, create_signature, create_lot_item, sku_update_status,
    sample_update_test_result, batch_qa_review,
    create_crm_account, crm_account_update_status, crm_account_update, crm_account_attach_document,
    batch_plan_update, batch_record_crude_oil_weight, batch_record_distilled_oil_weight,
    org_update_license_id, crm_account_create_note, create_order,
    order_add_item,
    order_update_account, order_attach_document,
    order_cancel_item, order_create_note,
    order_update_status, order_payment_status,
    order_item_add_shipment,
    order_item_map_to_lot_item,
    create_shipment,
    shipment_update_shipping_address,
    shipment_update_tracking_number,
    shipment_packaged,
    shipment_update_shipped_date,
    shipment_shipped,
    shipment_delivered,
    shipment_update_delivered_date,
    create_capa,
    capa_update_description,
    capa_initiate,
    capa_dismiss,
    capa_close,
    capa_add_note,
    capa_add_link,
    capa_link_disable,
    capa_add_action,
    capa_approve_action_plan,
    capa_action_update,
    capa_action_cancel,
    capa_action_close,
    receive_consumable_lot,
    consumable_class_update_status,
    create_consumable_class,
    consumable_lot_use_items,
    user_create,
    user_update_enabled,
    consumable_lot_destroy_items,
    consumable_lot_update_status,
    consumable_lot_return_items,
    record_transaction,
    update_transaction_total_amount,
    record_transaction_allocation,
    create_recall,
    recall_close,
    recall_active,
    recall_update_detail,
    sop_assignment_delete,
    sop_assignment_sign,
    sop_version_update,
    sop_assign_department,
    sop_assign_user,
    sop_uploaded_new_version,
    department_create,
    sop_set_status,
    org_update_date_format,
    org_update_date_time_format,
    org_update_metric_system,
    org_update_temperature_scale,
    org_update_upload_formats,
    org_update_currency,
    org_update_enable_signature,
    org_update_enable_lot_approval,
    org_update_use_batch_name_column_as_link,
    batch_record_cured_weight,
    create_organization,
    org_update_facility_details,
    org_update_tax_numbers,
    received_inventory_return,
    salvage_batch,
    lot_update_thc,
    lot_update_cbd,
    order_update,
    order_item_update,
    received_inventory_return,
    sku_update_gtin,
    create_deviation_report,
    deviation_report_create_assignment,
    deviation_report_status_update,
    deviation_report_assignment_status_update,
    deviation_report_attach_document,
    deviation_report_create_note,
    merge_batch,
    merge_lot,
    create_sanitation_activity,
    sop_add_link,
    deviation_report_add_link,
    create_invoice,
    receive_processor,
    send_processor,
    send_to_extraction,
    batch_record_final_extracted_weight,
    batch_add_additive,
    org_update_fallback_tax_value,
    update_fallback_tax,
    lot_review
)

from activities.activity_group import (
    batch_add_links,
)


from activities.external_activities import (
    create_external_order, 
    update_external_order,  
    external_order_payment_status,
    external_order_update_status,
    external_order_update_account,
    external_order_create_note,
    external_order_attach_document,
    external_order_add_item,
    external_order_item_update,
    external_order_cancel_item,
    external_order_item_map_to_lot_item,
    external_order_item_add_shipment,
    create_external_shipment,
    external_shipment_packaged,
    external_shipment_shipped,
    external_shipment_delivered,
    external_shipment_update_shipped_date,
    external_shipment_update_delivered_date,
    external_shipment_update_tracking_number,
    external_shipment_update_shipping_address,
    create_external_crm_account,
    external_crm_account_update,
)


ACTIVITIES = {
    'admin_adjustment': admin_adjustment.AdminAdjustment,
    'approve_received_inventory': approve_received_inventory.ApproveReceivedInventory,
    'batch_record_harvest_weight': batch_record_harvest_weight.BatchRecordBudHarvestWeight,
    'complete_destruction': complete_destruction,
    'batch_record_dry_weight': batch_record_dry_weight.RecordDryWeight,
    'split_batch': split_batch.SplitBatch,
    'batch_record_cured_weight': batch_record_cured_weight.RecordCuredWeight,
    'batch_record_final_yield': batch_record_final_yield.BatchRecordFinalYield,
    'complete_oil_extraction': complete_oil_extraction.CompleteOilExtraction,
    'create_activity_log': create_activity_log.CreateActivityLog,
    'create_batch': create_batch.CreateBatch,
    'create_mother_batch': create_mother_batch.CreateMotherBatch,
    'transfer_mother_plants_to_mother_batch': transfer_mother_plants_to_mother_batch.TransferMotherPlantsToMotherBatch,
    'transfer_batch_plant_to_mother_batch': transfer_batch_plant_to_mother_batch.TransferBatchPlantToMotherBatch,
    'create_mother': create_mother.CreateMother,
    'update_mother_status': update_mother_status.MotherUpdateStatus,
    'create_rule': create_rule,
    'destroy_material': destroy_material.DestroyMaterial,
    'germinate_seeds': germinate_seeds.GerminateSeeds,
    'metrics_collect_branch_count': metrics_collect_branch_count.MetricsCollectBranchCount,
    'metrics_collect_bud_density': metrics_collect_bud_density.MetricsCollectBudDensity,
    'metrics_collect_bud_moisture': metrics_collect_bud_moisture.MetricsCollectBudMoisture,
    'metrics_collect_bud_diameter': metrics_collect_bud_diameter.MetricsCollectBudDiameter,
    'metrics_collect_height': metrics_collect_height.MetricsCollectHeight,
    'metrics_collect_internodal_space': metrics_collect_internodal_space.MetricsCollectInternodalSpace,
    'metrics_collect_trichome_color': metrics_collect_trichome_color.MetricsCollectTrichomeColor,
    'metrics_record_deficiency': metrics_record_deficiency.MetricsRecordDeficiency,
    'org_update_license_id': org_update_license_id.OrgUpdateLicenseId,
    'org_update_theme': org_update_theme.OrgUpdateTheme,
    'org_update_date_format': org_update_date_format.OrgUpdateDateFormat,
    'org_update_date_time_format': org_update_date_time_format.OrgUpdateDateTimeFormat,
    'org_update_metric_system': org_update_metric_system.OrgUpdateMetricSystem,
    'org_update_temperature_scale': org_update_temperature_scale.OrgUpdateTemperatureScale,
    'org_update_currency': org_update_currency.OrgUpdateCurrency,
    'org_update_upload_formats': org_update_upload_formats.OrgUpdateUploadFormats,
    'org_update_enable_signature': org_update_enable_signature.OrgUpdateEnableSignature,
    'org_update_enable_lot_approval': org_update_enable_lot_approval.OrgUpdateEnableLotApproval,
    'org_update_use_batch_name_column_as_link': org_update_use_batch_name_column_as_link.OrgUpdateUseBatchNameColumnAsLink,
    'plants_add_pesticide': plants_add_pesticide.PlantsAddPesticide,
    'plants_add_fertilizer': plants_add_fertilizer.PlantsAddFertilizer,
    'plants_add_ipm': plants_add_ipm.PlantsAddIPM,
    'plants_defoliate': plants_defoliate.PlantsDefoliate,
    'plants_flush': plants_flush.PlantsFlush,
    'plants_prune': plants_prune.PlantsPrune,
    'propagate_cuttings': propagate_cuttings.PropagateCuttings,
    'queue_for_destruction': queue_for_destruction.QueueForDestruction,
    'receive_inventory': receive_inventory.ReceiveInventory,
    'transfer_inventory': transfer_inventory.TransferInventory,
    'unset_room': unset_room.UnsetRoom,
    'update_room': update_room.UpdateRoom,
    'update_rule': update_rule,
    'update_stage': update_stage.UpdateStage,
    'update_inventory_name': update_inventory_name.UpdateInventoryName,
    'sample_sent_to_lab': sample_sent_to_lab.SampleSentToLab,
    'create_sample': create_sample.CreateSample,
    'batch_visual_inspection': batch_visual_inspection.BatchVisualInspection,
    'create_sku': create_sku.CreateSKU,
    'sku_update_status': sku_update_status.UpdateStatus,
    'sample_lab_result_received': sample_lab_result_received.SampleLabResultReceived,
    'create_lot': create_lot.CreateLot,
    'create_lot_item': create_lot_item.CreateLotItem,
    'lot_review': lot_review.LotReview,
    'sample_update_test_result': sample_update_test_result.SampleUpdateTestResult,
    'batch_qa_review': batch_qa_review.BatchQaReview,
    'create_crm_account': create_crm_account.CreateCRMAccount,
    'crm_account_update_status': crm_account_update_status.CRMAccountUpdateStatus,
    'crm_account_update': crm_account_update.CRMAccountUpdate,
    'crm_account_attach_document': crm_account_attach_document.CRMAccountAttachDocument,
    'batch_plan_update': batch_plan_update.BatchPlanUpdate,
    'batch_record_crude_oil_weight': batch_record_crude_oil_weight.RecordCrudeOilWeight,
    'batch_record_distilled_oil_weight': batch_record_distilled_oil_weight.RecordDistilledOilWeight,
    'crm_account_create_note': crm_account_create_note.CRMAccountCreateNote,
    'create_order': create_order.CreateOrder,
    'create_external_order' : create_external_order.CreateExternalOrder,
    'update_external_order' : update_external_order.UpdateExternalOrder,
    'order_add_item': order_add_item.OrderAddItem,
    'order_update_account': order_update_account.OrderUpdateAccount,
    'order_cancel_item': order_cancel_item.OrderCancelItem,
    'order_attach_document': order_attach_document.OrderAttachDocument,
    'order_create_note': order_create_note.OrderCreateNote,
    'order_update_status': order_update_status.OrderUpdateStatus,
    'order_payment_status':order_payment_status.OrderPaymentStatus,
    'create_shipment': create_shipment.CreateShipment,
    'order_item_add_shipment': order_item_add_shipment.OrderItemAddShipment,
    'order_item_map_to_lot_item': order_item_map_to_lot_item.OrderItemMapToLotItem,
    'shipment_update_shipping_address': shipment_update_shipping_address.ShipmentUpdateShippingAddress,
    'shipment_update_tracking_number': shipment_update_tracking_number.ShipmentUpdateTrackingNumber,
    'shipment_packaged': shipment_packaged.ShipmentPackaged,
    'shipment_update_shipped_date': shipment_update_shipped_date.ShipmentUpdateShippedDate,
    'shipment_shipped': shipment_shipped.ShipmentShipped,
    'shipment_delivered': shipment_delivered.ShipmentDelivered,
    'shipment_update_delivered_date': shipment_update_delivered_date.ShipmentUpdateDeliveredDate,
    'create_capa': create_capa.CreateCapa,
    'capa_update_description': capa_update_description.CapaUpdateDescription,
    'capa_initiate': capa_initiate.CapaInitiate,
    'capa_dismiss': capa_dismiss.CapaDismiss,
    'capa_close': capa_close.CapaClose,
    'capa_add_note': capa_add_note.CapaAddNote,
    'capa_add_link': capa_add_link.CapaAddLink,
    'capa_link_disable': capa_link_disable.CapaLinkDisable,
    'capa_add_action': capa_add_action.CapaAddAction,
    'capa_approve_action_plan': capa_approve_action_plan.CapaApproveActionPlan,
    'capa_action_update': capa_action_update.CapaActionUpdate,
    'capa_action_cancel': capa_action_cancel.CapaActionCancel,
    'capa_action_close': capa_action_close.CapaActionClose,
    'receive_consumable_lot': receive_consumable_lot.ReceiveConsumableLot,
    'consumable_class_update_status': consumable_class_update_status.UpdateStatus,
    'create_consumable_class': create_consumable_class.CreateConsumableClass,
    'consumable_lot_use_items': consumable_lot_use_items.ConsumableLotUseItems,
    'user_create': user_create.CreateUser,
    'user_update_enabled': user_update_enabled.UserUpdateEnabled,
    'consumable_lot_destroy_items': consumable_lot_destroy_items.ConsumableLotDestroyItems,
    'consumable_lot_update_status': consumable_lot_update_status.UpdateStatus,
    'record_transaction': record_transaction.RecordTransaction,
    'record_transaction_allocation': record_transaction_allocation.RecordTransactionAllocation,
    'create_recall': create_recall.CreateRecall,
    'recall_close': recall_close.CloseRecall,
    'recall_update_detail':  recall_update_detail.UpdateRecallDetail,
    'recall_active': recall_active.ActiveRecall,
    'update_transaction_total_amount': update_transaction_total_amount.UpdateTransactionTotalAmount,
    'consumable_lot_return_items': consumable_lot_return_items.ConsumableLotReturnItems,
    'create_signature': create_signature.CreateSignature,
    'sop_assignment_delete': sop_assignment_delete.SopAssignmentDelete,
    'sop_assignment_sign': sop_assignment_sign.SopAssignmentSign,
    'sop_version_update': sop_version_update.SopVersionUpdate,
    'sop_assign_department': sop_assign_department.SopAssignDepartment,
    'sop_assign_user': sop_assign_user.SopAssignUser,
    'sop_uploaded_new_version': sop_uploaded_new_version.SopUploadedNewVersion,
    'department_create': department_create.DepartmentCreate,
    'sop_set_status': sop_set_status.SopSetStatus,
    'create_organization': create_organization.CreateOrganization,
    'org_update_facility_details': org_update_facility_details.OrgUpdateFacilityDetails,
    'received_inventory_return': received_inventory_return.ReceivedInventoryReturnItems,
    'org_update_tax_numbers': org_update_tax_numbers.OrgUpdateTaxNumbers,
    'salvage_batch': salvage_batch.SalvageBatch,
    'lot_update_thc': lot_update_thc.UpdateThc,
    'lot_update_cbd': lot_update_cbd.UpdateCbd,
    'order_update': order_update.OrderUpdate,
    'order_item_update': order_item_update.OrderItemUpdate,
    'received_inventory_return': received_inventory_return.ReceivedInventoryReturnItems,
    'sku_update': sku_update_gtin.UpdateGTINBarcodes,
    'create_deviation_report': create_deviation_report.CreateDeviationReport,
    'deviation_report_create_assignment': deviation_report_create_assignment.DeviationReportCreateAssignment,
    'deviation_report_status_update': deviation_report_status_update.DeviationReportUpdateStatus,
    'deviation_report_assignment_status_update': deviation_report_assignment_status_update.DeviationReportUpdateAssignment,
    'deviation_report_attach_document': deviation_report_attach_document.DeviationReportAttachDocument,
    'deviation_report_create_note': deviation_report_create_note.DeviationReportCreateNote,
    'merge_batch': merge_batch.MergeBatch,
    'merge_lot': merge_lot.MergeLot,
    'create_sanitation_activity': create_sanitation_activity.CreateSanitationActivity,
    'send_to_extraction': send_to_extraction.SendToExtraction,
    'batch_record_final_extracted_weight': batch_record_final_extracted_weight.BatchRecordFinalExtractedWeight,
    'batch_add_additive': batch_add_additive.BatchAddAdditive,

    'create_external_order':create_external_order.CreateExternalOrder,
    'update_external_order':update_external_order.UpdateExternalOrder,  
    'external_order_update_status':external_order_update_status.ExternalOrderUpdateStatus,
    'external_order_payment_status' : external_order_payment_status.ExternalOrderPaymentStatus,
    'external_order_update_account':external_order_update_account.ExternalOrderUpdateAccount,
    'external_order_create_note':external_order_create_note.ExternalOrderCreateNote,
    'external_order_attach_document':external_order_attach_document.ExternalOrderAttachDocument,
    'external_order_add_item':external_order_add_item.ExternalOrderAddItem,
    'external_order_item_update':external_order_item_update.ExternalOrderItemUpdate,
    'external_order_cancel_item':external_order_cancel_item.ExternalOrderCancelItem,
    'external_order_item_map_to_lot_item':external_order_item_map_to_lot_item.ExternalOrderItemMapToLotItem,
    'external_order_item_add_shipment':external_order_item_map_to_lot_item.ExternalOrderItemMapToLotItem,
    'create_external_shipment':create_external_shipment.CreateExternalShipment,
    'external_shipment_packaged':external_shipment_packaged.ExternalShipmentPackaged,
    'external_shipment_shipped':external_shipment_shipped.ExternalShipmentShipped,
    'external_shipment_delivered':external_shipment_delivered.ExternalShipmentDelivered,
    'external_shipment_update_shipped_date':external_shipment_update_shipped_date.ExternalShipmentUpdateShippedDate,
    'external_shipment_update_delivered_date':external_shipment_update_delivered_date.ExternalShipmentUpdateDeliveredDate,
    'external_shipment_update_tracking_number':external_shipment_update_tracking_number.ExternalShipmentUpdateTrackingNumber,
    'external_shipment_update_shipping_address':external_shipment_update_shipping_address.ExternalShipmentUpdateShippingAddress,
    'create_external_crm_account': create_external_crm_account.CreateExternalCRMAccount,
    'external_crm_account_update': external_crm_account_update.ExternalCRMAccountUpdate,
    'batch_add_links': batch_add_links.BatchAddLinks,
    'sop_add_link': sop_add_link.SopAddLink,
    'deviation_report_add_link': deviation_report_add_link.DeviationReportAddLink,
    'create_invoice': create_invoice.CreateInvoice,
    'send_processor': send_processor.SendProcessor,
    'receive_processor': receive_processor.ReceiveProcessor,
    'create_invoice': create_invoice.CreateInvoice,
    'org_update_fallback_tax_value': org_update_fallback_tax_value.OrgUpdateFallbackTaxValue,
    'update_fallback_tax': update_fallback_tax.UpdateFallbackTax,
}
