from marshmallow import Schema, fields

# validate all the inventories
class LotSchema(Schema):
    id = fields.Int()
    name = fields.Str(required=True)
    variety = fields.Str(required=True)
    variety_id = fields.Int(required=True)
    to_qty = fields.Float(required=True)
    to_qty_unit = fields.Str(required=True)
    from_qty = fields.Float(required=True)
    from_qty_unit = fields.Str(required=True)
    to_room = fields.Str(required=True)
    weighed_by = fields.Email(required=True)
    checked_by = fields.Email(required=True)
    approved_by = fields.Email(required=True)
    from_inventory_id = fields.Int(required=True)
    inventory_type = fields.Str(required=True)
    lot_name = fields.Str(missing=None)
    external_product_id = fields.Str()
    merged_inventories = fields.Str()
    scale_name = fields.Str(allow_none=True)
    mother_type = fields.Str()
    timestamp = fields.DateTime(required=True)


class TransferLotSchema(Schema):
    id = fields.Int()
    name = fields.Str(required=True)
    variety = fields.Str(required=True)
    variety_id = fields.Int(required=True)
    to_qty = fields.Float(required=True)
    to_qty_unit = fields.Str(required=True)
    from_qty = fields.Float(required=True)
    from_qty_unit = fields.Str(required=True)
    weighed_by = fields.Email(required=True)
    checked_by = fields.Email(required=True)
    approved_by = fields.Email(required=True)
    from_inventory_id = fields.Int(required=True)
    to_inventory_id = fields.Int(required=True)
    inventory_type = fields.Str(required=True)
    lot_name = fields.Str(missing=None)
    external_product_id = fields.Str()
    merged_inventories = fields.Str()
    scale_name = fields.Str(allow_none=True)
    mother_type = fields.Str()
    timestamp = fields.DateTime(required=True)